// Type declarations for @liquicode/jsonstor-postgres
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// Documents are stored in a PostgreSql database.

declare module '@liquicode/jsonstor-postgres'
{

	//---------------------------------------------------------------------
	// A column this adapter is allowed to create.
	//
	// Used only while the adapter is creating the table. Afterwards the table itself is
	// the authority on what its columns are.

	export interface ColumnDefinition
	{
		Name: string;
		/** The SQL type. A missing or non-string value takes the adapter's default. */
		Type?: string;
		/** True for the column which carries the document identifier. */
		Key?: boolean;
	}


	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** The name or address of the PostgreSql server. Defaults to `"localhost"`. */
		Server?: string;
		/** The service port of the PostgreSql server. Defaults to `5432`. */
		Port?: number;
		/** The name of the database to use. It must already exist; this adapter never creates a database. */
		Database: string;
		/** The schema holding the table. Every statement names it, so the connection's search path does not decide which table is used. Defaults to `"public"`. */
		Schema?: string;
		/** The name of the table to use. */
		Table: string;
		/** The column to treat as the document identifier. Empty means none. Defaults to `""`. */
		IdField?: string;
		/** The user to connect as. */
		UserName: string;
		/** That user's password. Pass an empty string for none - the setting itself is required. */
		Password: string;
		/** Allow the adapter to create the schema, the table, and the columns it is told to create. It never adds a column because a document had a field. Defaults to `false`. */
		ModifySchema?: boolean;
		/** The column which stores the document as JSON text. Empty means none, and then every field must already be a column. Created when missing if `ModifySchema` is `true`. Defaults to `""`. */
		PayloadColumn?: string;
		/** Store the whole document in the payload, making the other columns an index over it. When `false` the payload holds only the fields which have no column. Defaults to `false`. */
		PayloadSync?: boolean;
		/** Columns to create, as `{ Name, Type, Key }`. Used only when this adapter creates the table; afterwards the table itself is the authority. Defaults to `[]`. */
		Columns?: ColumnDefinition[];
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** Always `'jsonstor-postgres'`. The name this adapter registers under. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-postgres.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];

}
